name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.1', '8.2', '8.3']
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl
          coverage: none

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict"

      - name: "Determine composer cache directory"
        id: "determine-composer-cache-directory"
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.dir }}"
          key: "php-${{ matrix.php }}-composer-${{ matrix.dependency-version }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php }}-composer-${{ matrix.dependency-version }}-"

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Run psalm
        run: composer analyze -- --php-version=${{ matrix.php }}

      - name: Start server
        run: (php -S localhost:8000 -t ./tests/Server &) || /bin/true

      - name: Wait for server bootup
        run: sleep 3

      - name: Execute tests
        run: vendor/bin/phpunit
